### ISSUE TITLE
Possible bug when {frontmatter} is not included

### ISSUE THREAD

**Issue by dwsideriusNIST** [livecomsjournal/article_templates#37] opened 2017-11-03 19:49 UTC
New issue: if the \maketitle \begin{abstract}...\end{abstract} is not stated between \begin{frontmatter} and \end{frontmatter}, the entire document is rendered single column.

It's easy to spot and fix; question is whether there should be a warning or compilation error.

**Comment by davidlmobley** [comment] 2017-11-04 03:24
In general I'm all for having things tell people what the problem is, but I have no idea how easy this is to achieve with LaTeX...

**Comment by davidlmobley** [comment] 2017-11-23 14:09
Do you know whether this is easily achievable?

**Comment by dwsideriusNIST** [comment] 2017-12-01 14:56
Nope, this is far deeper into LaTeX than I usually dig.

**Comment by davidlmobley** [comment] 2017-12-01 16:55
@liantze any insights?

**Comment by liantze** [comment] 2017-12-02 10:18
That's right, and this is by design, not a bug—the `abstract` must be within `frontmatter` for the title/author/blurb/abstract to be rendered in the current layout. 

And yes, I can make it throw an error when `abstract` is used outside `frontmatter` (_"Nope nope nope, please put abstract inside the frontmatter environment"_). A warning is possible too; but I suppose an error would be more attention-grabbing for authors to notice the error and the solution. WDYT? Error or Warning?

**Comment by davidlmobley** [comment] 2017-12-02 13:34
An error sounds great. Thanks!

**Comment by davidlmobley** [comment] 2017-12-02 16:22
Resolved by #45 , @dwsideriusNIST

**Closed** 2017-12-02 16:23 UTC
Labels: help wanted

**Comment by dwsideriusNIST** [comment] 2017-12-04 13:26
Thanks, this works for me!
